# Generated by Django 3.2 on 2023-01-04 09:36

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_name', models.CharField(max_length=40, verbose_name='Roadmap Name')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, verbose_name='Topic Name')),
                ('topic_description', mdeditor.fields.MDTextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/')),
                ('roadmap_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='roadmap.roadmap')),
            ],
        ),
    ]
