# Generated by Django 3.2 on 2023-01-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptopic',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority Value'),
            preserve_default=False,
        ),
    ]
