# Generated by Django 3.2 on 2022-02-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('favourite_icon', models.ImageField(blank=True, null=True, upload_to='favourite_icon/')),
                ('keywords', models.CharField(blank=True, max_length=2000, null=True)),
                ('script_add', models.CharField(blank=True, max_length=5000, null=True)),
                ('privacy', models.TextField(blank=True, max_length=5000, null=True)),
                ('aboutus', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
