# Generated by Django 3.2 on 2022-02-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_siteconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='favourite_icon',
        ),
    ]
