# Generated by Django 3.2 on 2022-02-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
