# Generated by Django 3.2 on 2024-09-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
    ]
