# Generated by Django 3.2 on 2022-07-19 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
