# Generated by Django 3.2 on 2022-07-19 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20220719_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
