# Generated by Django 3.2 on 2022-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_auto_20220719_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='current_status',
            field=models.BooleanField(default=False, verbose_name='Currently Working'),
        ),
    ]
