# Generated by Django 3.2 on 2022-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_employment_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='current_status',
            field=models.BooleanField(default=True, verbose_name='Currently Working'),
        ),
    ]
