# Generated by Django 3.2 on 2022-07-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_employment_end_date_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='end_date_value',
        ),
    ]
