# Generated by Django 3.2 on 2022-07-19 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_employment_end_date_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2022, 7, 19)),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2022, 7, 19)),
        ),
    ]
