# Generated by Django 3.2 on 2022-07-19 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0010_auto_20220719_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='employment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
