# Generated by Django 3.2 on 2022-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0011_auto_20220719_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='employment',
            name='end_month',
            field=models.CharField(blank=True, max_length=255, verbose_name='End Month'),
        ),
        migrations.AddField(
            model_name='employment',
            name='end_year',
            field=models.CharField(blank=True, max_length=255, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_month',
            field=models.CharField(default='January', max_length=255, verbose_name='Start Month'),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_year',
            field=models.CharField(default='2015', max_length=255, verbose_name='Start Year'),
        ),
    ]
