# Generated by Django 3.2 on 2024-09-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_contact_id'),
    ]

    operations = [
    ]
