# Generated by Django 3.0.4 on 2020-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='live',
            field=models.TextField(blank=True, null=True),
        ),
    ]
