# Generated by Django 3.0.4 on 2020-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200325_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='short_desciption',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
