# Generated by Django 3.2 on 2024-09-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20240923_0538'),
    ]

    operations = [
    ]
