# Generated by Django 3.0.4 on 2020-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200325_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='downloadOrView',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='short_desciption',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
